name = "lucky"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "129.150.50.63"
UUID = "b457803d-93b6-40c2-90ec-5a9210c70901"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
