name = "lucky"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "129.150.50.63"
UUID = "13507332-fe92-43a1-8e88-11e9a666c2f9"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
